name: Deploy Smart Contract

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Print current directory
        run: pwd

      - name: List files in the current directory
        run: ls -la

      - name: List files in the parent directory
        run: ls -la ..

      - name: List files in the grandparent directory
        run: ls -la ../..

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Compile contracts
        run: npx hardhat compile

      - name: Deploy to RSK
        env:
          RSK_PRIVATE_KEY: ${{ secrets.RSK_PRIVATE_KEY }}
          RSK_RPC_URL: ${{ secrets.RSK_RPC_URL }}
        run: npx hardhat run scripts/deploy.js --network rsk